config/routes.rb
Rails.application.routes.draw do

  with_options only: [ :show, :index ] do
    resources :events
    resources :people
    resources :venues
  end
  
  resource :session, only: [ :new, :create, :destroy ] do
    post :token, constraints: { format: "json" }
  end

  resources :locales, only: [ :show ]

  get :me, controller: :people, action: :show
  get :now, controller: :now, action: :show

  with_options controller: :home do
    get :privacy, action: :privacy
    get :contact, action: :contact
    get :beta, action: :beta
    get :about, action: :about
    get :support, action: :support
    get :'apple-app-site-association', action: :apple_association
    root action: :index
  end

  scope '.well-known' do
    get :'apple-app-site-association', to: 'home#apple_association'
  end

  
end

app/models/event.rb
class Event
  attr_reader :data

  def self.find(id)
    Event.new API_CONNECTION.get("/v1/events/#{id}").body['event']
  end

  def initialize(data)
    @data = data
    puts "Event => #{data}"
  end
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < Admin::AdminController
  before_action :set_event, only: [ :show, :edit, :destroy, :update ]

  def index
    @events = Event.all
  end

  def show
  end

  # GET /events/new
  def new
    graph = user.facebook_graph

    if params[:facebook_id]
      event = graph.get_object(params[:facebook_id])
      event['facebook_id'] = event.delete 'id'

      venue = Venue.find_or_initialize_by(facebook_id: event['venue']['id'])
      event.delete 'venue'

      @event = Event.new(event)
      @event.venue = venue

      if event['owner']['id'] != venue.facebook_id
        person = Person.find_or_create_by(facebook_id: event['owner']['id'])
        @event.person = person
      end

      if event['privacy'] && event['privacy'] != 'OPEN'
        flash.now[:danger] = 'This is not a public event'
      end
    else
      @event = Event.new
    end

    not_answered = graph.get_object('/me/events/not_replied')
    attending = graph.get_object('/me/events/attending')

    @importable_events = not_answered + attending
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to [:admin, @event], notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to admin_events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def import

  end

  private
  # Never trust parameters from the scary internet, only allow the white list through.
  def event_params
    params.require(:event).permit(:start_time, :end_time, :name, :description, :venue_id, :person_id )
  end

  def set_event
    @event = Event.find(params[:id])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])
    @title = @event.data['name']
    @app_link = "events/#{@event.data['id']}"
    @image = @event.data['cover_photo_url']
  end
end

app/helpers/admin/events_helper.rb
module Admin::EventsHelper
end

app/helpers/events_helper.rb
module EventsHelper
  def natural_time(date_time)
    if date_time > DateTime.now
      "in #{distance_of_time_in_words_to_now date_time}"
    else
      "#{distance_of_time_in_words_to_now date_time} ago"
    end
  end
end

app/views/admin/events/_form.html.haml
= form_for [:admin, @event] do |f|
  - if @event.errors.any?
    #error_explanation
      %h2= "#{pluralize(@event.errors.count, "error")} prohibited this event from being saved:"
      %ul
        - @event.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :name
    = f.text_field :name, { class: 'form-control' }
  .form-group
    = f.label :start_time
    = f.datetime_select :start_time
  .form-group
    = f.label :end_time
    = f.datetime_select :end_time
  .form-group
    = f.label :description
    = f.text_area :description, class: 'form-control', rows: 10
  - if @event['owner']
    .form-group
      %label Owner
      %div
        %p.form-control-static= @event['owner']['name']
        = f.hidden_field :person_id
  - if @event.venue
    .form-group
      %label Venue
      %div
        %p.form-control-static= @event.venue.name
        = f.hidden_field :venue_id

  .actions
    = link_to 'Cancel', events_path, class: 'btn btn-default'
    = f.submit 'Save', class: 'btn btn-success'

app/views/admin/events/edit.html.haml
%h1.page-header
  Editing Event
  %small= @event.name

= render 'form'

= link_to 'Show', @event
\|
= link_to 'Back', events_path

app/views/admin/events/index.html.haml
%h1.page-header Listing Events

.panel.panel-default
  .panel-heading Events
  %table.table
    %thead
      %tr
        %th Name
        %th.com-md-2 Starts
        %th.col-md-2 Actions
    %tbody
      - @events.each do |event|
        %tr
          %td= link_to event.name, [:admin, event]
          %td= natural_time event.start_time
          %td
            = link_to 'Edit', edit_admin_event_path(event), class: 'btn btn-primary'
            = link_to 'Delete', [:admin, event], method: :delete, data: { :confirm => 'Are you sure?' }, class: 'btn btn-danger'
  .panel-footer
    = link_to 'New Event', new_admin_event_path, { class: 'btn btn-primary' }

app/views/admin/events/new.html.haml
%h1.page-header New Event

- if params[:facebook_id].nil?
  .row
    .panel.panel-default
      .panel-heading Import an Event
      %table.table
        %thead
          %tr
            %th Name
            %th Location
            %th Date
        %tbody
          - @importable_events.each do |event|
            %tr
              %td= link_to (truncate event['name'], length: 60), new_admin_event_path(facebook_id: event['id'])
              %td= event['location']
              %td= event['start_time']

.row
  .panel.panel-default
    .panel-heading Create an Event
    .panel-body
      = render 'form'

app/views/admin/events/show.html.haml
%h1.page-header= @event.name

.row
  = @event.description

= link_to 'Edit', edit_admin_event_path(@event), class: 'btn btn-primary'
= link_to 'Back', admin_events_path, class: 'btn btn-default'
= link_to 'Delete', [:admin, @event], method: :delete, data: { :confirm => 'Are you sure?' }, class: 'btn btn-danger'


- if Rails.env == 'development'
  .text-muted= @event.inspect